language: node_js
node_js:
  - 12

services:
  - docker

#  Pre-testing installs
install: 
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script: 
  - echo "no tests"

script:
  # Build images with docker compose
  - docker compose -f docker-compose-build.yaml build --parallel
  # list current images
  - docker images
  # tag images for upload 
  - docker tag udagram-api-feed chibkay/udagram-api-feed:v1
  - docker tag udagram-api-user chibkay/udagram-api-user:v1
  - docker tag udagram-frontend chibkay/udagram-frontend:v1
  - docker tag reverseproxy chibkay/reverseproxy:v1

after_success: 
  # login to docker using env variables from travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push images to docker
  - docker push chibkay/udagram-api-feed:v1
  - docker push chibkay/udagram-api-user:v1
  - docker push chibkay/udagram-frontend:v1
  - docker push chibkay/reverseproxy:v1
